############################
# Run a test using nose.
# requires: python-nose
nosetest:
	nosetests -v nose

# requires: python-coverage
coverage:
	nosetests --with-coverage ..


############################
# Run a test using unittest.
unittest:
	python ./suite.py
